New typescript template
UnlyEd/skeleton-generators pull request #11
Opened 2019-07-26 09:44 UTC by Demmonius

2019-07-26 09:45 UTC, Demmonius commented
Template testé et fonctionnel. Les tests unitaires fonctionnent aussi

2019-07-26 10:53 UTC, Vadorequest requested changes

2019-07-26 10:53 UTC, Vadorequest commented on templates/typescript-v3.5.2-MIT/README-CONDITIONAL-OPERATORS.md
> +
wut?

2019-07-26 10:53 UTC, Vadorequest commented on templates/typescript-v3.5.2-MIT/README.md
> +Then please check the conditions documentation [here](README-CONDITIONAL-OPERATORS.md)
wut?

2019-07-26 10:53 UTC, Vadorequest commented on templates/typescript-v3.5.2-MIT/README.md
> +Then please check the conditions documentation [here](README-CONDITIONAL-OPERATORS.md)
reprend un fichier readme standard, genre d'un autre template v12

2019-07-26 10:53 UTC, Vadorequest commented on templates/typescript-v3.5.2-MIT/package.json
> +  "name": "@unly/XXXPackage",
NON
regarde ce que j'ai fait dans les autre templates

2019-07-26 10:53 UTC, Vadorequest commented on templates/typescript-v3.5.2-MIT/package.json
> +    "url": "git+https://github.com/UnlyEd/XXX"
pareil ici et autres XXX

Voir https://github.com/UnlyEd/boilerplates-generator/blob/master/templates/node-v12.6.0-package-MIT/package.json

2019-07-27 16:52 UTC, Vadorequest requested changes

2019-07-27 16:52 UTC, Vadorequest commented on templates/typescript-v3.5.2-MIT/README.md
> +> Boilerplate currently broken due to webpack misconfiguration
relis ton readme au lieu de copier/coller bêtement

2019-07-29 13:49 UTC, Vadorequest approved these changes

2019-07-29 14:04 UTC, merged