New template for node10.10 - AWS
UnlyEd/skeleton-generators pull request #6
Opened 2019-07-11 09:25 UTC by Demmonius

2019-07-12 03:55 UTC, Vadorequest requested changes

2019-07-12 03:55 UTC, Vadorequest commented on templates/node-v10.10-aws-serverless/package.json
> +    "@jimdo/serverless-dotenv": "1.0.0",
à priori on peut utiliser notre version dès à présent

2019-07-12 03:55 UTC, Vadorequest commented on templates/node-v10.10-aws-serverless/package.json
> +    "aws-sdk": "2.296.0",
On peut supprimer ça, on l'utilise pas et ça évite de démarrer avec une version aws-sdk outdated car ça évolue vite

2019-07-12 03:55 UTC, Vadorequest commented on templates/node-v10.10-aws-serverless/serverless.yml
> +frameworkVersion: "=1.39.1"
utilise 1.46.0, met le cache à jour également, c'est la dernière version stable connue

2019-07-12 03:55 UTC, Vadorequest commented on templates/node-v10.10-aws-serverless/serverless.yml
> +  - '@unly/serverless-env-copy-plugin' # See https://github.com/UnlyEd/serverless-env-copy-plugin
Attention, il est pas dans le package.json

Fait un test de ce template, ça sert à rien de me faire un template s'il fonctionne pas quand j'en ai besoin, ça va juste me faire perdre du temps

2019-07-12 03:55 UTC, Vadorequest commented on templates/node-v10.10-aws-serverless/serverless.yml
> +  webpack:
Regarde ce que j'ai fait dans le cache:

```
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules:
      forceExclude:
        - aws-sdk
    packager: 'yarn'
    packagerOptions: {}
    excludeFiles: src/**/*.test.js
    keepOutputDirectory: true
```

2019-07-12 03:55 UTC, Vadorequest commented on templates/node-v10.10-aws-serverless/serverless.yml
> +  runtime: nodejs8.10
```
  name: aws
  runtime: nodejs10.x # AWS keeps up to date with the latest v10 version - See https://forum.serverless.com/t/node-10-lambdas-on-aws/8302/2
  versionFunctions: false # See https://serverless.com/framework/docs/providers/aws/guide/functions#versioning-deployed-functions
  logRetentionInDays: 60
```

Regarde et compare la config du cache ! sinon tu vas oublier plein de petits trucs importants
Si tu comprends pas des options, demandes moi

2019-07-12 03:55 UTC, Vadorequest commented on templates/node-v10.10-aws-serverless/serverless.yml
> +    product: ${self:service}
runtime

2019-07-12 03:55 UTC, Vadorequest commented on templates/node-v10.10-aws-serverless/serverless.yml
> +  region: ${opt:region, 'eu-west-1'} # Ireland by default, must always be Ireland
timeout

2019-07-12 03:55 UTC, Vadorequest commented on templates/node-v10.10-aws-serverless/src/functions/status.js
> +  }),
nodejs: process.version,

2019-07-12 14:42 UTC, Demmonius commented on templates/node-v10.10-aws-serverless/serverless.yml
> +  - '@unly/serverless-env-copy-plugin' # See https://github.com/UnlyEd/serverless-env-copy-plugin
C'est résolu mais modifié dans le package.json donc pas résolu pour github !

2019-07-12 14:43 UTC, Demmonius commented on templates/node-v10.10-aws-serverless/serverless.yml
> +  webpack:
Fichier correctement changé

2019-07-12 14:43 UTC, Demmonius commented on templates/node-v10.10-aws-serverless/serverless.yml
> +    product: ${self:service}
Done

2019-07-12 14:43 UTC, Demmonius commented on templates/node-v10.10-aws-serverless/serverless.yml
> +  region: ${opt:region, 'eu-west-1'} # Ireland by default, must always be Ireland
Done too

2019-07-12 14:43 UTC, Demmonius commented on templates/node-v10.10-aws-serverless/serverless.yml
> +  region: ${opt:region, 'eu-west-1'} # Ireland by default, must always be Ireland
Done

2019-07-12 15:03 UTC, merged

2019-07-12 15:05 UTC, Vadorequest commented on templates/node-v10.10-aws-serverless/.babelrc
> +  "presets": [
ça correspond pas à la config babel du cache @Demmonius vérifie

2019-07-12 15:05 UTC, Vadorequest commented on templates/node-v10.10-aws-serverless/.babelrc
> +  "presets": [
C'est pas le meme babel entre SLS et un projet node standard autant que je sache

2019-07-12 15:09 UTC, Demmonius commented on templates/node-v10.10-aws-serverless/.babelrc
> +  "presets": [
Ok je test

2019-07-13 07:07 UTC, Vadorequest commented
Et je te laisse gérer la pléthore d'alertes de sécurité https://github.com/UnlyEd/skeleton-generators/network/alerts